version: '3'

services:
  db:
    image: postgres:14.2-alpine
    container_name: db-estoque
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: microservico_estoque_development
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"  # Mapeando a porta 5434 do host para 5432 do contêiner

  cda_postgres:
    image: postgres:14.2-alpine
    restart: always
    volumes:
      - cda_postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=501'
    environment:
      POSTGRES_DB: cda-db
      POSTGRES_USER: administrador
      POSTGRES_PASSWORD: "microservAuth2024"
    ports:
      - "5432:5432"  # Mantendo a porta 5432 do host para 5432 do contêiner

  microservico-estoque:
    image: viniciusr21/mc-rails123:incompleto
    env_file: .env
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: microservico_estoque_development
      DB_USERNAME: vinicius
      DB_PASSWORD: 123
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db

  microservico-validacao:
    image: itsamemarcus/inf-016:latest
    ports:
      - "8080:8080"
    depends_on:
      - cda_postgres

volumes:
  postgres_data:
  cda_postgres_data:

networks:
  default:
    name: myapp_default

